version: 0.2

phases:
  pre_build:
    commands:
      - mkdir -p ~/.ssh
      - echo "$GITHUB_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval $(ssh-agent -s)
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-add ~/.ssh/id_rsa
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/$SOURCE_DIR"
      - terraform init
      - terraform apply -auto-approve
