version: 0.2

phases:
  build:
    commands:
      - git config --global --add safe.directory /codebuild/src0
      - git fetch --unshallow

      - CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | xargs -n1 dirname | sort -u)
      - echo "Source directory to check: $SOURCE_DIR"
      - echo "Directories with changes in the last commit:"
      - echo "$CHANGED_DIRS"
      - |
        if echo "$CHANGED_DIRS" | grep -q "^${SOURCE_DIR}$"; then
          echo "Changes detected in '$SOURCE_DIR'. Proceeding with the pipeline."
        else
          echo "No changes detected in '$SOURCE_DIR'. Stopping this pipeline path."
          exit 1
        fi
