version: 0.2

phases:
  install:
    runtime-versions:
      # We need git installed to run our check
      python: 3.9
    commands:
      # Tell git that the checkout directory is safe to use
      - git config --global --add safe.directory /codebuild/src0
      # CodePipeline does a shallow clone (only the last commit). We need at least one more commit (HEAD~1) to run a diff.
      - git fetch --unshallow

build:
  commands:
    - CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | xargs -n1 dirname | sort -u)
    - echo "Source directory to check: $SOURCE_DIR"
    - echo "Directories with changes in the last commit:"
    - echo "$CHANGED_DIRS"

    # Use the pipe '|' to treat the entire if-then-else block as a single command
    - |
      if echo "$CHANGED_DIRS" | grep -q "^${SOURCE_DIR}$"; then
        echo "Changes detected in '$SOURCE_DIR'. Proceeding with the pipeline."
      else
        echo "No changes detected in '$SOURCE_DIR'. Stopping this pipeline path."
        exit 1
      fi
