version: 0.2

phases:
  build:
    commands:
      - echo "Checking for any relevant file changes in the repository..."
      - git config --global --add safe.directory /codebuild/src0
      - git fetch --unshallow

      - |
        # This regex excludes the .gitignore file and any file ending in .md
        CHANGE_COUNT=$(git diff --name-only HEAD~1 HEAD | grep -vE '^(\.gitignore|.*\.md)$' | wc -l)

        echo "Found $CHANGE_COUNT relevant file change(s)."

        # If the count is greater than 0, succeed. Otherwise, fail.
        if [ "$CHANGE_COUNT" -gt 0 ]; then
          echo "Relevant changes detected. Proceeding with the pipeline."
          exit 0
        else
          echo "No relevant changes detected (only doc/git changes). Stopping the pipeline."
          exit 1
        fi
