version: 0.2

phases:
  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -backend=false
      - tflint --init
      - tflint

  post_build:
    commands:
      - echo "lint complete"
