version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.12
       nodejs: 24
    commands:
      - cd /usr/bin
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y terraform-${TF_VERSION}
      - python -V
      - pip3 install checkov==${CHECKOV_VERSION}
      - export PYENV_VERSION=3.12
      - npm install -g xunit-viewer
  pre_build:
    commands:
      - mkdir -p ~/.ssh
      - echo "$GITHUB_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval $(ssh-agent -s)
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-add ~/.ssh/id_rsa
  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR/$SOURCE_DIR"
      - |
        if [ -z "${CHECKOV_SKIPS}" ]; then 
          checkov --directory ./ --skip-path ./deploy -o junitxml --download-external-modules true > checkov.xml || $CONTINUE_ON_SAST_FAIL
        else
          checkov --directory./ --skip-path ./deploy --skip-check ${CHECKOV_SKIPS} -o junitxml --download-external-modules true > checkov.xml || $CONTINUE_ON_SAST_FAIL 
        fi
      - xunit-viewer --results checkov.xml --output checkov-$CODEBUILD_RESOLVED_SOURCE_VERSION.html
      - echo "Checkov complete. Report available in CodeBuild project > Reports" 
      
reports:
  ${SAST_REPORT_ARN}:
    files:
      - checkov.xml
    base-directory: $CODEBUILD_SRC_DIR/$SOURCE_DIR
    file-format: JUNITXML
artifacts:
  files:
    - checkov-$CODEBUILD_RESOLVED_SOURCE_VERSION.html
  base-directory: $CODEBUILD_SRC_DIR/$SOURCE_DIR
